fix(ci)

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -28,9 +28,15 @@ jobs:
         id: extract_version
         shell: pwsh
         run: |
-          $version = (Select-String -Path "Stub/Config.cs" -Pattern 'Version = "([0-9.]+)"').Matches.Groups[1].Value
-          Write-Host "Version extracted: $version"
-          echo "::set-output name=release_version::$version"
+          $configContent = Get-Content -Path "Stub/Config.cs"
+          $version = $configContent | Select-String -Pattern 'Version = "([0-9.]+)"' | ForEach-Object { $_.Matches.Groups[1].Value }
+          if (-not $version) {
+            Write-Error "Failed to extract version. Ensure that 'Version = \"X.X.X\"' exists in the file."
+            exit 1
+          } else {
+            Write-Host "Version extracted: $version"
+            echo "::set-output name=release_version::$version"
+          }
 
       - name: Archive Stealerium 🧱
         uses: thedoctor0/zip-release@master
